apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlas-db-controller
  namespace: atlas
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: atlas:controller:db
rules:
- apiGroups:
  - ""
  - "atlasdb.infoblox.com"
  resources:
  - services
  - pods
  - secrets
  - databaseservers
  - databases
  - databaseschemas
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: atlas:controller:db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: atlas:controller:db
subjects:
- kind: ServiceAccount
  name: atlas-db-controller
  namespace: atlas
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atlas-db-controller
  namespace: atlas 
spec: 
  replicas: 1 
  template: 
    metadata:
      labels:
        app: atlas-db-controller
    spec: 
      serviceAccountName: atlas-db-controller
      containers:
      - name: atlas-db-controller
        image: infobloxcto/atlas.dbcontroller:latest
        imagePullPolicy: Always
        args:
          - "-resync=3m"
